# SPDX-FileCopyrightText: 2022 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/compas/keycloak/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/compas/reverse-proxy/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
