config:
  keycloak:
    keycloakUrl: "http://compas.local/"
    clientUrl: "http://compas.local/"

service:
  environment:
    public:
      keycloak:
        realm: compas

keycloak:
  postgresql:
    enabled: false

  ingress:
    enabled: true;
    hostname: "compas.local"
    annotations:
      alb.ingress.kubernetes.io/group.name: "openscd"
      external-dns.alpha.kubernetes.io/hostname: compas.local
      kubernetes.io/ingress.class: nginx

  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"

  externalDatabase:
    host: "postgres-keycloak"
    port: 5432
    user: keycloak
    database: "keycloak"
    existingSecret: keycloak-db-credentials

  extraVolumeMounts:
    - name: keycloak-realm-cm
      mountPath: /opt/bitnami/keycloak/data/import/keycloak_compas_realm.json
      subPath: keycloak_compas_realm.json

  extraVolumes:
    - name: keycloak-realm-cm
      configMap:
        name: keycloak-realm-cm

  secrets:
    dbPassword: weFSG7zn9VIOul3
