# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

version: "3.9"

services:
  basex:
    image: "basex/basexhttp:9.5.2"
    ports:
      - "1984:1984"
    volumes:
      - basex-data-volume:/srv/basex/data
      - basex-repo-volume:/srv/basex/repo
      - basex-webapp-volume:/srv/basex/webapp

  keycloak:
    build: keycloak
    ports:
      - "8089:8080"
    environment:
      - KEYCLOAK_FRONTEND_URL=http://localhost/auth/
      - PROXY_ADDRESS_FORWARDING=true

  scl-data-service:
    image: "lfenergycompas/compas-scl-data-service:0.6.2"
    environment:
      - BASEX_HOST=basex
      - BASEX_PORT=1984
      - JWT_VERIFY_KEY=http://keycloak:8080/auth/realms/compas/protocol/openid-connect/certs
      - JWT_VERIFY_ISSUER=http://localhost/auth/realms/compas
      - JWT_VERIFY_CLIENT_ID=scl-data-service
      - JWT_GROUPS_PATH=resource_access/scl-data-service/roles
      - USERINFO_NAME_CLAIMNAME=name
      - USERINFO_WHO_CLAIMNAME=name
    depends_on:
      - basex
      - keycloak

  cim-mapping:
    image: "lfenergycompas/compas-cim-mapping:0.6.0"
    environment:
      - JWT_VERIFY_KEY=http://keycloak:8080/auth/realms/compas/protocol/openid-connect/certs
      - JWT_VERIFY_ISSUER=http://localhost/auth/realms/compas
      - JWT_VERIFY_CLIENT_ID=cim-mapping
      - JWT_GROUPS_PATH=resource_access/cim-mapping/roles
      - USERINFO_WHO_CLAIMNAME=name
    depends_on:
      - keycloak

  open-scd:
    image: "lfenergycompas/compas-open-scd:v0.7.0-compas-4"
    depends_on:
      - scl-data-service
      - cim-mapping

  reverse-proxy:
    build: reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - keycloak
      - scl-data-service
      - cim-mapping
      - open-scd

volumes:
  basex-data-volume:
  basex-repo-volume:
  basex-webapp-volume:
