# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

version: "3.9"

services:
  open-scd:
    image: "lfenergycompas/compas-open-scd:v0.4.1-compas-1"
    ports:
      - "8080:80"
    depends_on:
      - scl-data-service
  scl-data-service:
    image: "lfenergycompas/compas-scl-data-service:0.0.4"
    ports:
      - "9090:8080"
    depends_on:
      - basex
  basex:
    image: "basex/basexhttp:9.5.2"
    ports:
      - "1984:1984"
    volumes:
      - basex-volume:/srv/basex/data

  cim-mapping:
    image: "lfenergycompas/compas-cim-mapping:0.0.2"
    ports:
      - "9091:8080"

  keycloak:
    build: keycloak
    ports:
      - "8089:8080"

volumes:
  basex-volume: