# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

version: "3.9"

services:
  basex:
    image: "basex/basexhttp:9.5.2"
    ports:
      - "1984:1984"
    volumes:
      - basex-data-volume:/srv/basex/data
      - basex-repo-volume:/srv/basex/repo
      - basex-webapp-volume:/srv/basex/webapp

  keycloak:
    build: keycloak

  scl-data-service:
    image: "lfenergycompas/compas-scl-data-service:0.1.1"
    environment:
      - BASEX_HOST=basex
      - BASEX_PORT=1984
      - AUTH_SERVER_URL=http://keycloak:8080/auth/realms/compas
      - AUTH_CLIENT_ID=scl-data-service
    depends_on:
      - basex

  cim-mapping:
    image: "lfenergycompas/compas-cim-mapping:0.1.0"

  open-scd:
    image: "lfenergycompas/compas-open-scd:v0.6.0-compas"
    depends_on:
      - scl-data-service
      - cim-mapping
      - keycloak

  reverse-proxy:
    build: reverse-proxy
    ports:
      - "8080:80"
    depends_on:
      - scl-data-service
      - cim-mapping
      - open-scd

volumes:
  basex-data-volume:
  basex-repo-volume:
  basex-webapp-volume:
