# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

version: "3.9"

services:
  postgresql:
    labels:
      compas: true
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=compas
      - PGDATA=/var/lib/postgresql/data/compas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - postgresql-data-volume:/var/lib/postgresql/data

  keycloak:
    build:
      context: ./keycloak
      args:
        COMPAS_HOSTNAME: ${COMPAS_HOSTNAME}
    labels:
      compas: true
    ports:
      - "8089:8080"
    environment:
      - KEYCLOAK_FRONTEND_URL=http://${COMPAS_HOSTNAME}/auth/
      - KEYCLOAK_HOSTNAME=${COMPAS_HOSTNAME}
      - KEYCLOAK_HTTP_PORT=80
      - PROXY_ADDRESS_FORWARDING=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
      interval: 30s
      timeout: 10s
      retries: 5

  scl-data-service:
    labels:
      compas: true
    image: "lfenergy/compas-scl-data-service:0.9.4-postgresql"
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_DB=compas
      - JWT_VERIFY_KEY=http://keycloak:8080/auth/realms/compas/protocol/openid-connect/certs
      - JWT_VERIFY_ISSUER=http://${COMPAS_HOSTNAME}/auth/realms/compas
      - JWT_VERIFY_CLIENT_ID=scl-data-service
      - JWT_GROUPS_PATH=resource_access/scl-data-service/roles
      - USERINFO_NAME_CLAIMNAME=name
      - USERINFO_WHO_CLAIMNAME=name
      - USERINFO_SESSION_WARNING=20
      - USERINFO_SESSION_EXPIRES=30
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/compas-scl-data-service/q/health/ready"]
      interval: 15s
      timeout: 10s
      retries: 5
    depends_on:
      - postgresql
      - keycloak

  cim-mapping:
    labels:
      compas: true
    image: "lfenergy/compas-cim-mapping:0.8.3"
    environment:
      - JWT_VERIFY_KEY=http://keycloak:8080/auth/realms/compas/protocol/openid-connect/certs
      - JWT_VERIFY_ISSUER=http://${COMPAS_HOSTNAME}/auth/realms/compas
      - JWT_VERIFY_CLIENT_ID=cim-mapping
      - JWT_GROUPS_PATH=resource_access/cim-mapping/roles
      - USERINFO_WHO_CLAIMNAME=name
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/compas-cim-mapping/q/health/ready"]
      interval: 15s
      timeout: 10s
      retries: 5
    depends_on:
      - keycloak

  scl-auto-alignment:
    labels:
      compas: true
    image: "lfenergy/compas-scl-auto-alignment:0.2.1"
    environment:
      - JWT_VERIFY_KEY=http://keycloak:8080/auth/realms/compas/protocol/openid-connect/certs
      - JWT_VERIFY_ISSUER=http://${COMPAS_HOSTNAME}/auth/realms/compas
      - JWT_VERIFY_CLIENT_ID=scl-auto-alignment
      - JWT_GROUPS_PATH=resource_access/scl-auto-alignment/roles
      - USERINFO_WHO_CLAIMNAME=name
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/compas-scl-auto-alignment/q/health/ready"]
      interval: 15s
      timeout: 10s
      retries: 5
    depends_on:
      - keycloak

  scl-validator:
    labels:
      compas: true
    image: "lfenergy/compas-scl-validator:0.1.1"
    ports:
      - "9093:8080"
    environment:
      - JWT_VERIFY_KEY=http://keycloak:8080/auth/realms/compas/protocol/openid-connect/certs
      - JWT_VERIFY_ISSUER=http://${COMPAS_HOSTNAME}/auth/realms/compas
      - JWT_VERIFY_CLIENT_ID=scl-validator
      - JWT_GROUPS_PATH=resource_access/scl-validator/roles
      - USERINFO_WHO_CLAIMNAME=name
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/compas-scl-validator/q/health/ready"]
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/ocl:/data/ocl
      - ./data/nsdoc:/data/nsdoc
    depends_on:
      - keycloak

  open-scd:
    labels:
      compas: true
    image: "lfenergy/compas-open-scd:v0.12.0.2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - scl-data-service
      - cim-mapping
      - scl-auto-alignment
      - scl-validator

  reverse-proxy:
    labels:
      compas: true
    build:
      context: ./reverse-proxy
      args:
        COMPAS_HOSTNAME: ${COMPAS_HOSTNAME}
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - keycloak
      - scl-data-service
      - cim-mapping
      - scl-auto-alignment
      - scl-validator
      - open-scd

volumes:
  postgresql-data-volume:
