name: AWS Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - name: read-docker-compose
        id: read_docker_compose
        uses: jbutcher5/read-yaml@main 
        with:
          file: './compas/docker-compose-postgresql.yml'
          key-path: '["services", "scl-data-service", "image"]'

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ github.workspace }}/aws/task-executions/compas-scl-data-service.json
          container-name: CoMPAS-Scl-Data-Service
          image: ${{ steps.read_docker_compose.outputs.data }}
          environment-variables: |
            POSTGRESQL_PASSWORD=bar
            POSTGRESQL_USERNAME=${{ secrets.JWT_VERIFY_KEY }}
        env: 
          JWT_VERIFY_KEY: ${{ secrets.JWT_VERIFY_KEY }}
      - name: Read task definition
        id: gist
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ steps.task-def.outputs.task-definition }}
          
      - name: Update gist
        uses: gorgbus/gist-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
        with:
          action: "update"
          gist_id: "7f705fb9c876557d31e15724fba5c61f"
          file_name: "task-description.json"
          content: ${{ steps.gist.outputs.content }}
