name: AWS Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: read-docker-compose
        uses: jbutcher5/read-yaml@main  
        id: read_docker_compose
        with:
          file: 'compas/docker-compose-postgresql.yml'
          key-path: "['services']"
          
      - name: use-yaml-file
        run: |
          echo namespace: ${{ steps.read_docker_compose.outputs.data }}

