name: AWS Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - name: read-docker-compose
        id: read_docker_compose
        uses: jbutcher5/read-yaml@main 
        with:
          file: './compas/docker-compose-postgresql.yml'
          key-path: '["services", "scl-data-service", "image"]'

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ github.workspace }}/aws/task-executions/compas-scl-data-service.json
          container-name: CoMPAS-Scl-Data-Service
          image: ${{ steps.read_docker_compose.outputs.data }}

      - name: use-yaml-file
        run: |
          echo namespace: ${{ steps.task-def.outputs.task-definition }}

      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/pascalwilbrink/7f705fb9c876557d31e15724fba5c61f
          gist_title: Example Gist Title
          gist_description: Example Gist Description
          github_file: ${{ steps.task-def.outputs.task-definition }}
