name: AWS Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: read-docker-compose
        uses: actions-tools/yaml-outputs@v2
        id: read_docker_compose
        with:
          file-path: ${{ github.workspace }}/compas/docker-compose-postgresql.yml

      - name: use-yaml-file
        run: |
          echo namespace: ${{ steps.read_docker_compose.outputs.services__scl-data-service__image }}

