# SPDX-FileCopyrightText: 2023 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Deploy CoMPAS OpenSCD on AWS

on:
  push:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1


      - name: read-docker-compose
        id: read_docker_compose
        uses: jbutcher5/read-yaml@main
        with:
          file: './compas/docker-compose-postgresql.yml'
          key-path: '["services", "open-scd", "image"]'
      - name: Render CoMPAS OpenSCD Container
        id: render-compas-openscd
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ github.workspace }}/aws/task-definitions/compas-openscd.json
          container-name: CoMPAS-OpenSCD
          image: ${{ steps.read_docker_compose.outputs.data }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-compas-openscd.outputs.task-definition }}
          service: "CoMPAS-OpenSCD"
          cluster: ${{ secrets.AWS_CLUSTER }}
