# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Run all integration tests

on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache register
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Start containers
        run: docker-compose -f "docker/docker-compose.yml" up -d --build
        env:
          COMPAS_HOSTNAME: docker_reverse-proxy_1
      - name: Wait until containers started
        run: sh ./bin/docker-wait-on-containers.sh

      - name: Created output directory (chromium)
        run: mkdir -p target/chromium
      - name: Execute integration tests (chromium)
        run: |
          docker run -e BROWSER=chromium \
            -e ROBOT_OPTIONS="-v url:http://docker_reverse-proxy_1/" \
            -v $(pwd)/target/chromium:/opt/robotframework/reports:Z \
            -v $(pwd)/integration-testing:/opt/robotframework/tests:Z \
            --user $(id -u):$(id -g) \
            --network=docker_default \
            ppodgorsek/robot-framework:latest

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker/docker-compose.yml" down -v
