# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Run all integration tests

on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache register
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Start containers
        run: docker-compose -f "compas/docker-compose.yml" up -d --build
        env:
          COMPAS_HOSTNAME: compas_reverse-proxy_1
      - name: Wait until containers started
        run: sh ./bin/docker-wait-on-containers.sh

      - name: Created output directory (firefox)
        run: mkdir -p target/firefox

#&& chmod -R 777 target
#      - name: Execute integration tests (firefox)
#        run: |
#          docker run --rm \
#                     --user $(id -u):$(id -g) \
#                     --network=compas_default \
#                     -v $(pwd)/target/firefox:/output \
#                     -v $(pwd)/integration-testing/:/test \
#                     marketsquare/robotframework-browser:latest \
#                     bash -c "robot -d /output -v browser:firefox -v url:http://compas_reverse-proxy_1/ /test"
#
#                     --ipc=host --security-opt seccomp=seccomp_profile.json \

      - name: Execute integration tests (firefox)
        run: |
          docker run --rm -e BROWSER=firefox \
            -e ROBOT_OPTIONS="-v url:http://compas_reverse-proxy_1/" \
            -v $(pwd)/target/firefox:/opt/robotframework/reports:Z \
            -v $(pwd)/integration-testing:/opt/robotframework/tests:Z \
            --user $(id -u):$(id -g) \
            --network=compas_default \
            ppodgorsek/robot-framework:latest

      - name: Stop containers
        if: always()
        run: docker-compose -f "compas/docker-compose.yml" down -v
