# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Run all integration tests

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache register
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Start containers
        run: docker-compose -f "docker/docker-compose.yml" up -d --build

      - name: Wait until containers started
        run: sh ./bin/docker-wait-on-containers.sh health=starting

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker/docker-compose.yml" down -v

      - name: Wait until containers stopped
        if: always()
        run: sh ./bin/docker-wait-on-containers.sh status=running
